id: genpatsu-location-fukui
version: 1.0.0
name: Genpatsu Location Fukui
description: Show nuclear power plant locations in Fukui with CSV data.
author: Kuni
extensions: []
widgets: []
actions: []
themes: []
visualizer:
  scripts:
    - "https://cooneywalker.github.io/reearth_plugins/genpatsu-location-fukui/index.js"
